export enum TokenType {
  IDENTIFIER = 'identifier',
  INTEGER = 'integer',
  PLUS = 'plus',
  MINUS = 'minus',
  MULTIPLY = 'multiply',
  DIVIDE = 'divide',
  MODULO = 'modulo',
  MATCH = 'match',
  EQUALS = 'equals',
  NOT_EQUALS = 'not equals',
  GREATER_THAN = 'greater than',
  GREATER_THAN_OR_EQUAL = 'greater than or equal',
  LESS_THAN = 'less than',
  LESS_THAN_OR_EQUAL = 'less than or equal',
  AND = 'and',
  OR = 'or',
  NOT = 'not',
  OPEN_PARENTHESIS = 'open paren',
  CLOSE_PARENTHESIS = 'close paren',
  TRUE = 'true',
  FALSE = 'false',
  EOF = 'eof',
}
